name: Check

on: push

jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.8
      - name: Build
        run: flutter build web
      - name: Run lint
        run: flutter analyze
      - name: Run test
        run: flutter test
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: rfa-skill-selection
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_ACTIONS }}
